import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import { Footer, Header, Sidebar } from '~widgets/index';
import "~styles/index.scss";
import styles from "./layout.module.scss";


const noto = Noto_Sans_KR({ subsets: ['latin', 'cyrillic'] });

export const metadata: Metadata = {
  title: 'Udemy - My top app',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body className={`${noto.className} ${styles.page}`}>
        <div className = {styles.container}>
          <Header className = {styles.header}/>
          <Sidebar className = {styles.sidebar}/>
            < >
              {children}
            </>
          <Footer className = {styles.footer}/>
        </div>
      </body>
    </html>
  );
}
